config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  # root "productns#index"
  get "pages/about"

  resources :books
  resources :authors

  resources :students
  resources :faculties
  
  # Active record Query Interface Routes
  get 'search', to:"employees#search"
  get 'employees/results'
  post '/increaseOrder', to: "employees#increaseOrder"
  post '/decreaseOrder', to: "employees#decreaseOrder"
  resources :employees

  # Advance Active Record Query Interface Routes
  get "products/activeTrue"
  get "pages/advance_query_interface"
  resources :products
  resources :customers
  resources :orders
  get "comments/like", to: "comments#like"
  resources :comments

  # Active Record Association
  get "events/home"
  # get "comments/add_comment"

  get "users/enroll"
  get "users/unenroll"
  

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :events
  resources :users, except: [:new]
  resources :categories

  # Rails_Routing

  get "index", to: "orderns#index"
  resources :productns do
    resources :orderns 
  end  
  
  namespace :business do
    get "/:id/preview", to: "customerns#preview"
    get 'search', to:"customerns#search"
    resources :customerns, only: [:index, :new, :create, :edit, :update] do
      member do
        match "delete_customer", via:[:delete]
      end
    end
  end

  # layouts and rendering

  get 'home', to:'myuser#home'

  devise_for :myusers
  resources :myproducts
  resources :myorders

  # Action View Form Helpers
  get 'searched', to:"employeens#searched"
  resources :employeens

  # API-only application
  namespace :api do
    namespace :v1 do
      get "searched", to: 'articles#searched'
      get "comment_search", to: 'acomments#comment_search'
      resources :articles do
        resources :acomments
      end
    end
  end

  # Testing Rails Application
  resources :test_products
  # Action mailer basics
  resources :userns

  # Working With javascript in rails
  resources :jusers do
    member do
      get "profile", to: 'jusers#profile'
      get "changepassword", to: 'jusers#changepassword'
      patch "changepassword_update"
    end
  end
end

app/models/test_product.rb
class TestProduct < ApplicationRecord
  belongs_to :myuser

  validates :product_name, :price,  :description, presence: true
  validates :product_name, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :product_name
end

app/controllers/test_products_controller.rb
class TestProductsController < ApplicationController
  
  before_action :set_product, only: [:show, :edit, :update, :destroy] 
  before_action :authenticate_myuser!

  def index
    @products = TestProduct.all
  end
  
  def new
    @product = TestProduct.new
  end
  
  def create
    @product = TestProduct.create(product_params)
    if @product.save
      redirect_to test_products_path
    else
      render "new"
    end
  end
  
  def edit  
  end
  
  def update
    if @product.update(product_params)
      redirect_to test_product_path
    else
      render "edit"
    end
  end
  
  def show
  end
  
  def destroy
    if @product.destroy
      redirect_to test_products_path
    end
  end

  private

  def product_params
    params.require(:test_product).permit(:product_name, :price, :description, :myuser_id)
  end

  def set_product
    @product = TestProduct.find(params[:id])
  end
end

app/helpers/test_products_helper.rb
module TestProductsHelper
end

app/views/test_products/edit.html.erb
<div class="container">
  <h1>Create a new Product</h1>

  <% if @product.errors.any? %>
    <h2> The following error(s) prevented the Product from being saved </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with(model: @product,local: true) do |f| %>
    
    <p>
      <%= f.text_field :product_name, class:"form-control", placeholder:"Enter Product Name"%>
    </p>
    <p>
      <%= f.number_field :price, class:"form-control", placeholder:"Enter Product Name"%>
    </p>
    <p>
      <%= f.text_area :description, class:"form-control", placeholder:"Enter Product Name"%>
    </p>

    <p>
      <%= f.submit %>
    </p>
      
  <% end %>

  <%= link_to "Return to Products Listing", test_products_path, class:"btn btn-info" %>
<div>

app/views/test_products/index.html.erb
<div class="container">
  <h1>Products List</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>description</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product|%>
      <tr>
        <td><%= product.product_name%></td>
        <td><%= product.price%></td>
        <td><%= product.description%></td>
        <td><%= link_to "Show", test_product_path(product), class:"btn btn-primary"%></td>
        <td><%= link_to "Edit", edit_test_product_path(product), class:"btn btn-info"%></td>
        <td><%= button_to "Delete", test_product_path(product), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger"%></td>
      </tr>
      <% end%>
    </tbody>
  </table>

  <p><%= link_to "Add new Product", new_test_product_path, class:"btn btn-primary" %></p>
</div>
  

app/views/test_products/new.html.erb
<div class="container">
  <h1>Create a new Product</h1>

  <% if @product.errors.any? %>
    <h2> The following error(s) prevented the Product from being saved </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with scope: :test_product, url:test_products_path, local: true do |f| %> 
      
    <p>
      <%= f.text_field :product_name, class:"form-control", placeholder:"Enter Product Name"%>
    </p>
    <p>
      <%= f.number_field :price, class:"form-control", placeholder:"Enter Product price"%>
    </p>
    <p>
      <%= f.text_area :description, class:"form-control", placeholder:"Enter Product Description"%>
    </p>
      <%= f.hidden_field :myuser_id, value: current_myuser.id %>

    <p>
      <%= f.submit %>
    </p>
      
  <% end %>

  <%= link_to "Return to Products Listing", test_products_path, class:"btn btn-info" %>
<div>

app/views/test_products/show.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4"><%= @product.product_name %></h1>
    <hr class="my-4">
  
    <%= link_to "Edit", edit_test_product_path(@product), class:"btn btn-primary" %> <br> <br>
    <%= button_to "Delete", test_product_path(@product), class:"btn btn-secondary" ,method: :delete, data: {confirm: "Are you sure?"} %> <br>
    <%= link_to "Return to Category Listing", test_products_path, class:"btn btn-info" %>
  </div>
</div>