config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  # root "productns#index"
  get "pages/about"

  resources :books
  resources :authors

  resources :students
  resources :faculties
  
  # Active record Query Interface Routes
  get 'search', to:"employees#search"
  get 'employees/results'
  post '/increaseOrder', to: "employees#increaseOrder"
  post '/decreaseOrder', to: "employees#decreaseOrder"
  resources :employees

  # Advance Active Record Query Interface Routes
  get "products/activeTrue"
  get "pages/advance_query_interface"
  resources :products
  resources :customers
  resources :orders
  get "comments/like", to: "comments#like"
  resources :comments

  # Active Record Association
  get "events/home"
  # get "comments/add_comment"

  get "users/enroll"
  get "users/unenroll"
  

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :events
  resources :users, except: [:new]
  resources :categories

  # Rails_Routing

  get "index", to: "orderns#index"
  resources :productns do
    resources :orderns 
  end  
  
  namespace :business do
    get "/:id/preview", to: "customerns#preview"
    get 'search', to:"customerns#search"
    resources :customerns, only: [:index, :new, :create, :edit, :update] do
      member do
        match "delete_customer", via:[:delete]
      end
    end
  end

  # layouts and rendering

  get 'home', to:'myuser#home'

  devise_for :myusers
  resources :myproducts
  resources :myorders

  # Action View Form Helpers
  get 'searched', to:"employeens#searched"
  resources :employeens

  # API-only application
  namespace :api do
    namespace :v1 do
      get "searched", to: 'articles#searched'
      get "comment_search", to: 'acomments#comment_search'
      resources :articles do
        resources :acomments
      end
    end
  end

  # Testing Rails Application
  resources :test_products
  # Action mailer basics
  resources :userns

  # Working With javascript in rails
  resources :jusers do
    member do
      get "profile", to: 'jusers#profile'
      get "changepassword", to: 'jusers#changepassword'
      patch "changepassword_update"
    end
  end
end

app/models/customern.rb
class Customern < ApplicationRecord
  
  validates :name, presence: true
end

app/controllers/business/customerns_controller.rb
class Business::CustomernsController < ApplicationController

  before_action :set_customern, only: [:edit, :update]
  
  def index
    @customerns = Customern.all
  end
  
  def create
    @customern = Customern.create(customern_params)
    if @customern.save
      redirect_to business_customerns_path
    else
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    if @customern.update(customern_params)
      redirect_to business_customerns_path	
    else
      render "edit"
    end
  end

  # method to preview the customer
  def preview
    @customern = Customern.find(params[:id])
  end

  # methof to delete cusotmer
  def delete_customer 
    @customern = Customern.find(params[:id])
    if @customern.destroy
      redirect_to business_customerns_path
    end
  end

  # method to search for customer in list
  def search
    if params[:search].blank?
      redirect_to business_customerns_path
    else
      @parameter = params[:search.downcase]
      @customerns = Customern.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end
  end

  private

  def set_customern
    @customern = Customern.find(params[:id])
  end

  def customern_params
    params.require(:customern).permit(:name)
  end
end

app/views/business/customerns/edit.html.erb
<div class="container">
  <h1>Create a new Customer</h1>

  <%# print errors %>
  <% if @customern.errors.any? %>
    <h2> The following error(s) prevented the Book from being saved </h2>
    <ul>
      <% @customern.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%# form for editing cusotmer %>
  <%= form_with(model: [:business, @customern], local: true) do |f| %> 
    
    <div class="field form-group">
      <%= f.text_field :name, class:"form-control", placeholder:"Enter Name"%>
    </div><br>

    <div class="action">
      <%= f.submit class:"btn btn-primary" %>
    </div><br>
  <% end %>

  <%= link_to "Return to Customer Listing", business_customerns_path, class:"btn btn-info" %>
<div>

app/views/business/customerns/index.html.erb
<div class="container">
  <h1>Customers List</h1>

  <%# form for searching customer %>
  <%= form_tag business_search_path, :method => 'get' do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Search for Customer", class: "form-control" %>
      <div class="input-group-btn">
      <%= button_tag "Search", class: "btn btn-info glyphicon glyphicon-search", name: nil %>
      </div>
    </div>
  <% end %>

  <%# List all customers %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @customerns.each do |customer|%>
      <tr>
        <td><%= customer.name%></td>
        <td><%= link_to "Edit", edit_business_customern_path(customer), class:"btn btn-primary"%></td>
        <td><%= link_to "Preview", business_path(customer), class:"btn btn-secondary"%></td>
        <td><%= button_to "Delete", delete_customer_business_customern_path(customer), class:"btn btn-danger", method: :delete%></td>
      </tr>
      <% end%>
    </tbody>
  </table>

  <p><%= link_to "Add new customer", new_business_customern_path, class:"btn btn-success" %></p>
</div>
  

app/views/business/customerns/new.html.erb
<div class="container">
  <h1>Create a new Customer</h1>

  <%# form for creating new customer %>
  <%= form_with scope: :customern, url:business_customerns_path, local: true do |f| %> 

    <div class="field form-group">
      <%= f.text_field :name, class:"form-control", placeholder:"Enter Name"%>
    </div><br>

    <div class="action">
      <%= f.submit class:"btn btn-primary" %>
    </div><br>
      
  <% end %>

  <%= link_to "Return to Csutomer Listing", business_customerns_path, class:"btn btn-info" %>
<div>

app/views/business/customerns/preview.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-4"><%= @customern.name %></h1>
    <hr class="my-4">
  </div>
</div>

app/views/business/customerns/search.html.erb
<div class="container">
  <table class="table table-hover">

    <!--search result table-->
    <thead>
      <tr>
        <th>Name</th>
        </tr>
    </thead>
    <tbody>
      <% @customerns.each do |customer|%>
      <tr>
        <td><%= customer.name%></td>
        <td><%= link_to "Edit", edit_business_customern_path(customer), class:"btn btn-secondary"%></td>
        <td><%= link_to "Preview", business_path(customer), class:"btn btn-secondary"%></td>
      </tr>
      <% end%>
    </tbody>
  </table>
</div>