config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  # root "productns#index"
  get "pages/about"

  resources :books
  resources :authors

  resources :students
  resources :faculties
  
  # Active record Query Interface Routes
  get 'search', to:"employees#search"
  get 'employees/results'
  post '/increaseOrder', to: "employees#increaseOrder"
  post '/decreaseOrder', to: "employees#decreaseOrder"
  resources :employees

  # Advance Active Record Query Interface Routes
  get "products/activeTrue"
  get "pages/advance_query_interface"
  resources :products
  resources :customers
  resources :orders
  get "comments/like", to: "comments#like"
  resources :comments

  # Active Record Association
  get "events/home"
  # get "comments/add_comment"

  get "users/enroll"
  get "users/unenroll"
  

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :events
  resources :users, except: [:new]
  resources :categories

  # Rails_Routing

  get "index", to: "orderns#index"
  resources :productns do
    resources :orderns 
  end  
  
  namespace :business do
    get "/:id/preview", to: "customerns#preview"
    get 'search', to:"customerns#search"
    resources :customerns, only: [:index, :new, :create, :edit, :update] do
      member do
        match "delete_customer", via:[:delete]
      end
    end
  end

  # layouts and rendering

  get 'home', to:'myuser#home'

  devise_for :myusers
  resources :myproducts
  resources :myorders

  # Action View Form Helpers
  get 'searched', to:"employeens#searched"
  resources :employeens

  # API-only application
  namespace :api do
    namespace :v1 do
      get "searched", to: 'articles#searched'
      get "comment_search", to: 'acomments#comment_search'
      resources :articles do
        resources :acomments
      end
    end
  end

  # Testing Rails Application
  resources :test_products
  # Action mailer basics
  resources :userns

  # Working With javascript in rails
  resources :jusers do
    member do
      get "profile", to: 'jusers#profile'
      get "changepassword", to: 'jusers#changepassword'
      patch "changepassword_update"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/views/home/_header.html.erb
<nav class="navbar navbar-light bg-secondary fixed-top">
  <div class="container-fluid">
    
    <%= link_to "GADA Electronics", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">GADA Electronics</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <%= link_to "Home", root_path, class:"navbar-brand" %>
          </li>
          <li class="nav-item">
            <%= link_to "About us", home_about_path, class:"navbar-brand" %>    
          </li>
          <li class="nav-item">
            <%= link_to "Manage Stocks", products_path, class:"navbar-brand" %>
          </li>
        
        </ul>
        
      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<p> Launched in 2006, first one-of-its kind large format specialist retail electronics store, Croma, caters to over 12 Million happy customers for all of their multi-brand digital gadgets and home electronics.    Since   its inception, Croma has become synonymous for all electronics needs, both online & in-store, with a wide product range and tech-savvy staff with a will to help customers throughout their buying journeys.</p>

app/views/home/index.html.erb
<div class="container">
	<h1> Welcome to GADA Electronics</h1>
	<h3> Serving since 1995 from Bhachau, Katchh. </h3>
</div>