config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  # root "productns#index"
  get "pages/about"

  resources :books
  resources :authors

  resources :students
  resources :faculties
  
  # Active record Query Interface Routes
  get 'search', to:"employees#search"
  get 'employees/results'
  post '/increaseOrder', to: "employees#increaseOrder"
  post '/decreaseOrder', to: "employees#decreaseOrder"
  resources :employees

  # Advance Active Record Query Interface Routes
  get "products/activeTrue"
  get "pages/advance_query_interface"
  resources :products
  resources :customers
  resources :orders
  get "comments/like", to: "comments#like"
  resources :comments

  # Active Record Association
  get "events/home"
  # get "comments/add_comment"

  get "users/enroll"
  get "users/unenroll"
  

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :events
  resources :users, except: [:new]
  resources :categories

  # Rails_Routing

  get "index", to: "orderns#index"
  resources :productns do
    resources :orderns 
  end  
  
  namespace :business do
    get "/:id/preview", to: "customerns#preview"
    get 'search', to:"customerns#search"
    resources :customerns, only: [:index, :new, :create, :edit, :update] do
      member do
        match "delete_customer", via:[:delete]
      end
    end
  end

  # layouts and rendering

  get 'home', to:'myuser#home'

  devise_for :myusers
  resources :myproducts
  resources :myorders

  # Action View Form Helpers
  get 'searched', to:"employeens#searched"
  resources :employeens

  # API-only application
  namespace :api do
    namespace :v1 do
      get "searched", to: 'articles#searched'
      get "comment_search", to: 'acomments#comment_search'
      resources :articles do
        resources :acomments
      end
    end
  end

  # Testing Rails Application
  resources :test_products
  # Action mailer basics
  resources :userns

  # Working With javascript in rails
  resources :jusers do
    member do
      get "profile", to: 'jusers#profile'
      get "changepassword", to: 'jusers#changepassword'
      patch "changepassword_update"
    end
  end
end

app/models/productn.rb
class Productn < ApplicationRecord
  has_many :orderns
end

app/controllers/productns_controller.rb
class ProductnsController < ApplicationController
  
  before_action :set_productn, only: [:show, :edit, :update, :destroy]
  
  def index
    @productns = Productn.all
  end
  
  def new
    @productn = Productn.new
  end
  
  def create
    @productn = Productn.create(productn_params)
    if @productn.save
      redirect_to productns_path
    else
      render "new"
    end
  end
  
  def edit
  end
  
  def update
    if @productn.update(productn_params)
      redirect_to productn_path(@productn)
    else
      render "edit"
    end
  end

  def show
  end
  
  def destroy
    if @productn.destroy
      redirect_to productns_path
    end
  end

  private

  def set_productn
    @productn = Productn.find(params[:id])
  end

  def productn_params
    params.require(:productn).permit(:name, :rate)
  end
end

app/views/productns/edit.html.erb
<div class="container">
  <h1>UpdateProduct</h1>

  <%# print errors %>
  <% if @productn.errors.any? %>
    <h2> The following error(s) prevented the Book from being saved </h2>
    <ul>
      <% @productn.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>

  <%# form for editing product %>
  <%= form_with(model: @productn,local: true) do |f| %>   
    
    <div class="field form-group">
      <%= f.text_field :name, class:"form-control", placeholder:"Enter Name"%>
    </div><br>

    <div class="field form-group">
      <%= f.number_field :rate, class:"form-control", placeholder:"Enter Price"%>
    </div><br>

    <div class="action">
      <%= f.submit class:"btn btn-primary" %>
    </div><br>
      
  <% end %>

  <%= link_to "Return to Products Listing", productns_path, class:"btn btn-info" %>
<div>

app/views/productns/index.html.erb
<div class="container">
<br>

  <%# list all products %>
  <h1>Products List</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Rate</th>
      </tr>
    </thead>
    <tbody>
      <% @productns.each do |product|%>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.rate%></td>
        <td><%= link_to "Show", productn_path(product), class:"btn btn-primary"%></td>
        <td><%= link_to "Edit", edit_productn_path(product), class:"btn btn-secondary"%></td>
        <td><%= button_to "Delete", productn_path(product), class:"btn btn-danger", method: :delete, data: { confirm: "Are you sure?" }%></td> 
      </tr>
      <% end%>
    </tbody>
  </table>

  <p><%= link_to "Add new Product", new_productn_path, class:"btn btn-primary" %></p>
</div>
  

app/views/productns/new.html.erb
<div class="container">
  <h1>Create a new Product</h1>

  <%# print errors %>
  <% if @productn.errors.any? %>
    <h2> The following error(s) prevented the Book from being saved </h2>
    <ul>
      <% @productn.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>
 
  <%# form for creating new order %>
  <%= form_with scope: :productn, url:productns_path, local: true do |f| %> 
    
    <div class="field form-group">
      <%= f.text_field :name, class:"form-control", placeholder:"Enter Name"%>
    </div><br>

    <div class="field form-group">
      <%= f.number_field :rate, class:"form-control", placeholder:"Enter Price"%>
    </div><br>

    <div class="action">
      <%= f.submit class:"btn btn-primary" %>
    </div><br>
      
  <% end %>

  <%= link_to "Return to Products Listing", productns_path, class:"btn btn-info" %>
<div>

app/views/productns/show.html.erb
<div class="container">
  <%# shows product %>
  <div class="jumbotron">
    <h1 class="display-4"><%= @productn.name %></h1>
    <h2 class="lead">Price : <%= @productn.rate %></h2>

    <hr class="my-4">

    <%= link_to "Edit", edit_productn_path(@productn), class:"btn btn-primary" %> <br> <br>
    <%= button_to "Delete", productn_path(@productn), class:"btn btn-secondary" ,method: :delete, data: {confirm: "Are you sure?"} %> <br>
    <%= link_to "Return to Product Listing", productns_path, class:"btn btn-info" %>
    <%= link_to "Create new Order of this Product", new_productn_ordern_path(@productn), class:"btn btn-success" %>
  </div>

  <%# list all orders of specific product %>
  <% if @productn.orderns.any? %>

    <br>
    <h1>Orders List</h1>

    <table class="table table-hover">
    <thead>
      <tr>
        <th>Order ID</th>
        
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @productn.orderns.each do |order|%>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.quantity%></td>
        <td><%= link_to "Show", productn_ordern_path(@productn, order), class:"btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_productn_ordern_path(@productn, order), class:"btn btn-secondary" %></td>
        <td><%= link_to "Delete", productn_ordern_path(@productn, order), method: :delete, data: {confirm: "Are you Sure?"}, class:"btn btn-danger" %></td>
      </tr>
      <% end%>
    </tbody>
  </table>
  <% end %>
</div>